# Generated by Django 5.2.1 on 2025-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc_empresa', models.CharField(max_length=9)),
                ('fecha_proceso', models.CharField(max_length=100)),
                ('codigo_cliente', models.CharField(max_length=10)),
                ('moneda', models.CharField(max_length=3)),
                ('cuenta_bancaria_empresa', models.CharField(max_length=20)),
                ('cuenta_bancaria_empleado', models.CharField(max_length=20)),
                ('cedula_empleado', models.CharField(max_length=11)),
                ('monto_pagar', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nomina',
                'managed': False,
            },
        ),
    ]
